# Generated by Django 4.1 on 2023-03-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name', models.CharField(max_length=300)),
                ('parent_lattice', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=50)),
                ('host_lattice', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=50)),
                ('angle_range', models.CharField(max_length=50)),
                ('strain_max', models.CharField(max_length=50)),
                ('angle', models.FloatField()),
                ('strain', models.FloatField()),
            ],
        ),
    ]
