# Generated by Django 4.1.4 on 2022-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel1', models.CharField(max_length=100)),
                ('cel2', models.CharField(max_length=100)),
                ('max_strain', models.FloatField()),
                ('nr_epochs', models.IntegerField()),
            ],
        ),
    ]
